services:
  shared_db:
    image: mysql:8.0
    container_name: shared_db
    environment:
      MYSQL_ROOT_PASSWORD: ${SHARED_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${SHARED_MYSQL_DATABASE}
      MYSQL_USER: ${SHARED_MYSQL_USER}
      MYSQL_PASSWORD: ${SHARED_MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    env_file:
      - .env  
  council_db:
    image: mysql:8.0
    container_name: council_db
    environment:
      MYSQL_ROOT_PASSWORD: ${COUNCIL_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${COUNCIL_MYSQL_DATABASE}
      MYSQL_USER: ${COUNCIL_MYSQL_USER}
      MYSQL_PASSWORD: ${COUNCIL_MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    env_file:
      - .env  

  admission_db:
    image: mysql:8.0
    container_name: admission_db
    environment:
      MYSQL_ROOT_PASSWORD: ${ADMISSION_MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${ADMISSION_MYSQL_DATABASE}
      MYSQL_USER: ${ADMISSION_MYSQL_USER}
      MYSQL_PASSWORD: ${ADMISSION_MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    env_file:
      - .env  

  web:
    build: .
    container_name: web
    command: >
      bash -c "while ! nc -z shared_db 3306 || ! nc -z council_db 3306 || ! nc -z admission_db 3306; do sleep 1; done &&
               python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - shared_db
      - council_db
      - admission_db
      
volumes:
  data: