"""
Django settings for server project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # local apps
    'shared_tenant',
    'council',
    'admission',
]

MIDDLEWARE = [
    'shared_tenant.tenant_middleware.TenantMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'server.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'server.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': config('SHARED_MYSQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': config('SHARED_MYSQL_DATABASE', os.path.join(BASE_DIR, 'shared_db.sqlite3')),
        'USER': config('SHARED_MYSQL_USER', "myuser"),
        'PASSWORD': config('SHARED_MYSQL_PASSWORD', "sharedpassword"),
        'HOST': config('SHARED_DB_HOST', 'localhost'),
        'PORT': config('SHARED_PORT', '3306'),
    },
    'council_db': {
        'ENGINE': config('COUNCIL_MYSQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': config('COUNCIL_MYSQL_DATABASE', os.path.join(BASE_DIR, 'council_db.sqlite3')),
        'USER': config('COUNCIL_MYSQL_USER', "myuser"),
        'PASSWORD': config('COUNCIL_MYSQL_PASSWORD', "councilpassword"),
        'HOST': config('COUNCIL_DB_HOST', 'localhost'),
        'PORT': config('COUNCIL_PORT', '3306'),
    },
    'admission_db': {
        'ENGINE': config('ADMISSION_MYSQL_ENGINE', 'django.db.backends.sqlite3'),
        'NAME': config('ADMISSION_MYSQL_DATABASE', os.path.join(BASE_DIR, 'admission_db.sqlite3')),
        'USER': config('ADMISSION_MYSQL_USER', "myuser"),
        'PASSWORD': config('ADMISSION_MYSQL_PASSWORD', "admissionpassword"),
        'HOST': config('ADMISSION_DB_HOST', 'localhost'),
        'PORT': config('ADMISSION_PORT', '3306'),
    }
}

DATABASE_ROUTERS = ['server.db_routers.TenantRouter']

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
